# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastai_course',
                'doc_host': 'https://hitkumar.github.io',
                'git_url': 'https://github.com/hitkumar/fastai_course',
                'lib_path': 'fastai_course'},
  'syms': {'fastai_course.core': {'fastai_course.core.foo': ('core.html#foo', 'fastai_course/core.py')}}}
